version: '2'

services:
  example-db:
    container_name: example-db
    image: mongo:latest
    volumes:
      - ./db:/data
    restart: always

  example-db-backup:
    container_name: example-db-backup
    image: tiredofit/mongodb-backup
    links:
     - example-db
    volumes:
      - ./backups:/backups
    environment:
      - DB_HOST=example-db
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ

    restart: always


